<?php

namespace Tests\Browser;

use Laravel\Dusk\Browser;
use Tests\DuskTestCase;

class AuthTest extends DuskTestCase {

    public $faker;
    public $appUrl;
    public $pause = 1000;

    public function setUp(): void {

        $this->faker  = \Faker\Factory::create();
        $this->appUrl = env( 'APP_URL' );
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * @throws \Throwable
     */
    public function test_home_page() {
        $this->browse( function ( Browser $browser ) {
            $browser->visit( '/' )
                    ->waitForText( 'Soccer App' )
                    ->assertSee( 'Soccer App' );
        } );
    }

    /**
     * @throws \Throwable
     */
    public function test_register_user() {

        $name  = $this->faker->name;
        $email = $this->faker->email;

        $this->test_home_page();

        $this->browse( function ( Browser $browser ) use ( $name, $email ) {
            $browser->clickLink( 'Register' )
                    ->waitForText( 'Register' )
                    ->type( '#name', $name )
                    ->type( '#email', $email )
                    ->type( '#password', 'admin' )
                    ->type( '#password_confirmation', 'admin' )
                    ->pressAndWaitFor( 'Register' )
                    ->pause( $this->pause )
                    ->assertUrlIs( $this->appUrl . '/login' );
            $this->assertDatabaseHas( 'users', [ 'email' => $email ] );
        } );
    }

    /**
     * @throws \Throwable
     */
    public function test_login() {
        $email = "admin@test.com";
        $pass  = "admin";
        $this->browse( function ( Browser $browser ) use ( $email, $pass ) {

            $browser->visit( '/login' )
                    ->waitForText( 'Register' )
                    ->type( '#email', $email )
                    ->type( '#password', $pass )
                    ->pressAndWaitFor( 'Login' )
                    ->pause( $this->pause )
                    ->assertUrlIs( $this->appUrl . '/dashboard' );
        } );
    }

}
